test/index.test.ts
@jelhan Looks like `validation` can be a String[].
ref https://github.com/poteto/ember-changeset-validations/issues/228
=> Test: array of validations

src/index.ts
Stringifying and parsing again will throw when `obj` has a circular
structure which can exist when e.g. ember data relationships are values
in the changesets underlying object. Fixes #19
=> Don't stringify and parse the error object to and from json

src/index.ts
The order of those was different for a promise validation vs a plain
function validation. The trigger was called *before* the validation
handler when the validation is a promise.
Since the errors are added to the changeset in `_handleValidation` the
trigger for promise validations was called before that error was set.
=> Handle validation and trigger AFTER_VALIDATION_EVENT in the right order

src/utils/get-key-values.ts, test/utils/get-key-values.test.ts
=> Fixed changes getter

src/utils/is-object.ts, src/utils/validator-lookup.ts, test/index.test.ts
ref https://github.com/poteto/ember-changeset-validations/issues/235#issuecomment-619391822
=> Refactor validator-lookup to return primitive

src/utils/validator-lookup.ts, test/index.test.ts
=> Array of validations is possible

.eslintrc.js, src/index.ts, src/types/index.ts, src/utils/object-tree-node.ts, test/index.test.ts, test/utils/normalize-object.test.ts, test/utils/object-tree-node.test.ts, test/utils/set-deep.test.ts
Currently, accessing nodes at an arbitrary level of the tree is rather cumbersome.  Previous solutions involved handling intermediate objects (before the leaf nodes) by merging `CHANGES` and `CONTENT` to give the user a complete picture of the object.  This was a source of bugs.  If we didn't and we asked for `changeset.get('user')`, we may lose sibling keys.  
```js
{
user: {
name: 'scott', <-- this changed and in CHANGES
email: '@gmail.com' <-- this did not change and in CONTENT
}
}
```
In order to facilitate a better access model, we return a Proxy to access further values - either `CHANGES` or `CONTENT`.  The downside of this approach is `changeset.user` will not allow you to do is equal comparison `===`.
close #44 
ref https://github.com/poteto/ember-changeset/issues/483
=> Implement recursive object tree proxy to properly handle sibling keys

src/index.ts, src/types/index.ts, src/utils/object-tree-node.ts, test/utils/object-tree-node.test.ts
with `Ember.set(node, 'user.email')`, Ember will break up the key and set the value on each successive node down the tree.  As a result of us returning a Proxy at each level, we need to allow a setter at each level.
=> Ember requires us to add ProxyHandler#set

src/index.ts, test/index.test.ts
If we need to validate based on derived property, not the raw changes
the only place where we can put a getter to calculate the value of that
property is the changeset itself as it buffers all changes.
This PR is an attempt to make it work.
=> Validate changeset getter

README.md, src/index.ts, src/types/index.ts, src/utils/object-tree-node.ts, test/index.test.ts
```
const changeset = Changeset(model, lookupValidator(validations), null, { changesetKeys: ['name', 'email'] };
```
ref https://github.com/poteto/ember-changeset/issues/485
Tests to re-enable - https://github.com/poteto/ember-changeset/blob/b7a244b05b73698a60bb2eb552336934de179983/tests/integration/main-test.js#L188
=> Add user provided changesetKeys to 4th constructor arg to Changeset

src/index.ts, src/types/index.ts
After some recent changes this method became redundant.
We can just remove it and use this[key] as it will access the same
values using the top-level getter.
=> Get rid of _valueFor

src/utils/object-tree-node.ts, test/index.test.ts
close #62 
Ember.get will fail if the 1st arg is undefined
=> Protect safeGet from undefined values

src/utils/merge-deep.ts, src/utils/normalize-object.ts, test/index.test.ts
"value" was a key to indicate we have a Change...but it might not be a change
ref https://github.com/poteto/ember-changeset-validations/issues/110
=> Ensure that my super duper secret "value" key is allowed to be used

src/index.ts, src/utils/object-tree-node.ts, test/index.test.ts
This may help this issue and allow us to rely on Ember.get in ember-changeset.
https://github.com/poteto/ember-changeset/issues/502#issuecomment-642782851
=> Simplify #get logic with return early for primitive

src/utils/is-object.ts, test/utils/is-object.test.ts
RegExps are `typeof` object, so they get wrapped with ObjectTreeNode. Since you would never need to track the changes of a nested RegExp property, let's not do that.
=> Exclude RegExp objects from isObject test

src/index.ts, src/types/index.ts, src/utils/flatten-validations.ts, src/utils/validator-lookup.ts, test/index.test.ts
Previously, we only allowed objects, nested objects, functions and arrays
ref https://github.com/poteto/ember-changeset-validations/issues/197
=> Add Validator class support

README.md, src/index.ts, test/index.test.ts
Partial revert: #80 
ref https://github.com/poteto/ember-changeset/issues/354
In order to access `model.errors`, we need to persist those changes on the underlying model.  As a result, `unexecute` is opt in now instead of by default.
=> #unexecute if save fails

.github/workflows/ci.yml, package.json, src/index.ts, src/utils/array-object.ts, src/utils/merge-deep.ts, src/utils/object-tree-node.ts, src/utils/set-deep.ts, test/index.test.ts, test/utils/merge-deep.test.ts, test/utils/set-deep.test.ts
Repro of some weird behavior: https://runkit.com/nullvoxpopuli/validated-changeset-with-deep-arrays
I have a complex object with objects as array entries that I'd like to manage with a changeset. :D 
the example I have at work is:
```ts
{
// big object
listOfStuff: [
{
... stuff
},
{
... some stuff
} 
]
}
```
I suppose creating arrays when the property is undefined doesn't really make sense, because you can't know if the user does indeed want an array, or a if they want an object with numbered keys that would behave kinda like an array.
I propose that if a value is an array, we set at indicies, rather than properties on an object
=> Implement support for Arrays

.eslintrc.js, .github/workflows/ci.yml, package.json, src/index.ts, src/utils/handle-multiple-validations.ts, src/utils/is-object.ts, src/utils/merge-deep.ts, src/utils/object-tree-node.ts, test/index.test.ts
I asked about this in discord, cause it's weird, unexpected behavior, but: https://discord.com/channels/480462759797063690/483601670685720591/814174406678020120
```bash
validated-changeset on  fix-lint-ci [$!+] is 📦 v0.13.1 via ⬢ v14.15.4 
❯ npm run lint
validated-changeset on  fix-lint-ci [$!+] is 📦 v0.13.1 via ⬢ v14.15.4 
❯ node_modules/.bin/eslint . --ext=js,ts
NullVoxPopuli/validated-changeset/rollup.config.ts
4:13  error  Require statement not part of import statement  @typescript-eslint/no-var-requires
```
not sure why there is a difference. with `yarn`, there is no difference... :shrug: I guess. Maybe an npm upgrade resolves?
=> Fix lint ci

src/index.ts, src/types/index.ts, test/index.test.ts
=> [Bug]: Fix async validations

src/index.ts, src/utils/object-tree-node.ts, test/index.test.ts
=> Refactor: no unwrap for arrays

src/index.ts, src/utils/merge-deep.ts, src/utils/set-deep.ts, test/index.test.ts, test/utils/merge-deep.test.ts, test/utils/set-deep.test.ts
why is `typeof null === 'object'`?
silly JS
* If the target was set to null or undefined, we always want to return the source.
* There is nothing to merge.
*
* Without this explicit check, typeof null === typeof {any object-like thing}
* which means that mergeTargetAndSource will be called, and you can't merge with null
=> Support null merging

src/index.ts, test/index.test.ts
ref https://github.com/poteto/ember-changeset/pull/586
=> [Bugfix]: no underlying content path to key that was modified

src/index.ts, src/utils/set-deep.ts, test/index.test.ts
The issue here is we were mutating a nested `set` incorrectly once we reached the leaf key.  This caused bugs as shown in the tests.
ref https://github.com/poteto/ember-changeset/issues/592
=> [Bug]: setDeep does not respect re-setting top level Change object

src/utils/object-tree-node.ts, test/utils/object-tree-node.test.ts
Properties on an ember-data object do not has `hasOwnProperty` when the change value is an ember-data Model.
https://github.com/validated-changeset/validated-changeset/pull/45/commits
https://github.com/poteto/ember-changeset/issues/594
=> [Bug]: better support for ember-data objects

src/utils/object-tree-node.ts, src/utils/set-deep.ts, test/index.test.ts, test/utils/set-deep.test.ts
in Collaboration with @basandlin and @camskene  :tada: 
We ran in to an issue where `changeset.set('propertyPathin.A.NewlyCreated.Object', false)` would delete the newly created object.
Tests added to verify :heart:
=> Support setting properties to false

src/index.ts, test/index.test.ts
This PR prioritizes user data over Proxy instance getters/methods.
Currently, if a user has a method named `trigger` defined on their "model" (argument to Changeset), then it will be ignored in favor of the Changeset `trigger` method.  To ensure class based inheritance works as expected, we need to adjust the Proxy trap prioritization order.
1. Changes
2. Content
3. Changeset properties.
ref #122
=> Rework final phases of get trap

src/index.ts
This PR only ensures that on validate we only ever read from an untracked errors cache before writing to a tracked property.  While `ERRORS` (`_errors`) is not **write** only _yet_ (ideal state so that tracked properties are only ever written but never read from. This ensure no read-then-write issues in Ember), this PR does ensure `validate()` can be called on render in Ember.  Moreover, ensuring we only write to `CHANGES` is a much more involved effort.  This PR does not attempt to fix.
ref https://github.com/poteto/ember-changeset/issues/602
=> Bugfix: validate on render without backtracking Ember assertion

src/utils/object-tree-node.ts, test/utils/object-tree-node.test.ts
Previously the proxy only returned truthy values for the properties
and `undefined` otherwise.
- Fix this to return the original values
=> Return falsy properties values

src/index.ts, test/index.test.ts
restore method converted snapshot with nested keys
```
{
changes: { name: 'Jim Bob', address: { country: 'North Korea' } },
errors: {}
}
```
into changeset with changes like below
```
[
{ key: 'name', value: 'Jim Bob' },
{ key: 'address', value: { country: 'North Korea' } }
]
```
fixed it to be:
```
[
{ key: 'name', value: 'Jim Bob' },
{ key: 'address.country', value: 'North Korea' }
]
```
=> Fix restore method to work with nested keys

README.md, src/index.ts, src/types/index.ts, test/index.test.ts
Adds an `initValidate` changeset option that can be specified when creating an instance of a changeset. When this option is `true`, the changeset will be validated immediately upon creation.
The idea behind this feature is to support the use case where a form needs to start in an invalid state.
For example, we regularly do the following in the ember apps that I work on.
```js
constructor() {
super(...arguments);
this.changeset = new Changeset(
this.args.someModel,
lookupValidator(SomeValidations),
SomeValidations
);
this.changeset.validate()
}
```
However, this code no longer works in Ember 3.24.0 and above because it can require mutating the changeset `_errors` property multiple times within the same computation.
This will cause the following error.
Using the `initValidate: true` option, …
=> Allow a changeset to be created in a validated state

README.md, package-lock.json, package.json, src/types/index.ts, src/validated.ts, test/validated.test.ts
This PR adds a separate Changeset with yup compatibility.  Will be used to flush out new ideas.
Limited API compared to the original Changeset.
Yup Changeset - https://github.com/jquense/yup
- ✂️ save
- errors are required to be added to the Changeset in manually after `validate`
- ✂️ cast
- ✂️ merge
- validate takes a callback with the sum of changes.  In user land you will call `changeset.validate((changes) => yupSchema.validate(changes))`
ref https://github.com/validated-changeset/validated-changeset/issues/146
ref https://github.com/validated-changeset/validated-changeset/issues/144
```
let userSchema = object({
age: number().required().min(21)
});
let dummyChangeset = Changeset(dummyModel, userSchema);
dummyChangeset.set('age', 2);
try {
await dummyChangeset.validate(); …
```
=> ValidationChangeset with yup compatibility

src/index.ts, test/index.test.ts
Steps to reproduce
1. Create nested property on a changeset
2. Make it fail validation
3. Set it to a valid value and validate
4. Call `rollbackInvalid()`
5. Observe that the now valid property had been removed from the changesets `changes`.
I have created this PR with a fix for this, also added a test case that can be reviewed for reproduction (without the fix the test will fail)
=> fix rollbackInvalid removing valid changes

.github/workflows/plan-release.yml
@mansona Sorry about that, missed one lingering `npm` command on the release step. This should do it
=> Replace npm ci with pnpm install --frozen-lockfile to fix release step
