src/index.ts, src/types/index.ts
Ref https://github.com/poteto/ember-changeset/pull/393
=> Fix TS type error for "errors" property

src/utils/merge-deep.ts
https://github.com/poteto/ember-changeset/pull/397
=> Add safe set to merge deep

src/index.ts, src/types/index.ts, src/utils/get-key-values.ts, src/utils/is-changeset.ts, src/utils/key-in-object.ts, src/utils/merge-deep.ts, test/index.test.ts, test/utils/key-in-object.test.ts, test/utils/merge-deep.test.ts
https://github.com/poteto/ember-changeset/commits/master
Thank you to all who contributed!!
=> Bring in changes from embewr-changeset

package.json, test/index.test.ts
https://github.com/poteto/ember-changeset/issues/398
=> Nested properties disappearing after #set

src/index.ts, test/index.test.ts
Makes things a tad simpler in ref #13
=> Trigger "execute" registered callback on Changeset.execute

package.json
ref https://github.com/poteto/ember-changeset/pull/430
=> Types file is at root

test/index.test.ts
https://github.com/poteto/ember-changeset/issues/442
=> Test for adding date on changeset

README.md, src/index.ts, test/index.test.ts
https://github.com/poteto/ember-changeset-validations/issues/134
=> Add moar tests

src/index.ts, src/utils/set-deep.ts, test/index.test.ts, test/utils/set-deep.test.ts
ref https://github.com/poteto/ember-changeset/issues/452
@josemarluedke
=> #set within a Change instance

src/index.ts
https://github.com/poteto/ember-changeset/blob/v2.2.5/addon/index.ts#L221
=> Use safe get on safe func for Proxy

test/index.test.ts, test/utils/merge-deep.test.ts
ref https://github.com/poteto/ember-changeset/issues/457
=> Add some tests related to class based mergeDeep

src/index.ts, src/utils/is-leaf.ts, test/index.test.ts
ref https://github.com/poteto/ember-changeset/pull/467
=> Merge sibling keys with `get`

src/index.ts, test/index.test.ts
https://github.com/poteto/ember-changeset/issues/468
=> Safe-set with setter

src/index.ts
hasOwnProperty doesnt need special handling
=> Revert setter change

src/index.ts, src/utils/set-deep.ts
ref https://github.com/poteto/ember-changeset/issues/468
=> Safe set for set deep

test/index.test.ts, test/utils/set-deep.test.ts
https://github.com/poteto/ember-changeset/issues/470
=> Improved sibling key tests for #setDeep

src/index.ts, src/utils/is-leaf.ts, src/utils/is-object.ts, test/index.test.ts
=> Merge sibling keys #set

src/index.ts, src/utils/flatten-validations.ts, test/index.test.ts, test/utils/flatten-validations.test.ts
close https://github.com/poteto/ember-changeset/issues/478
=> Validate nested keys with validate/0

src/utils/set-deep.ts
=> use isObject

src/index.ts, test/index.test.ts
=> Ensure isPristine after execute

src/index.ts, test/index.test.ts
ref https://github.com/poteto/ember-changeset/pull/488
=> Detect if object has Change in object tree

src/index.ts, src/types/index.ts, src/utils/object-tree-node.ts, test/index.test.ts, test/utils/object-tree-node.test.ts
ref https://github.com/poteto/ember-changeset/pull/488/files
ref #59
=> Unwrap Proxy before passing to validator func

src/-private/empty.ts, src/index.ts, src/utils/mark-undefined-leaf-keys.ts, src/utils/normalize-object.ts, src/utils/object-tree-node.ts, test/index.test.ts, test/utils/mark-undefined-lefa-keys.test.ts, test/utils/normalize-object.test.ts, test/utils/object-tree-node.test.ts
close #65 
Maybe https://github.com/poteto/ember-changeset-validations/issues/110#issuecomment-638911041
=> Handle keys that were squashed and undefined

bin/test-external-changeset.js, src/index.ts
https://www.google.com/url?q=https://github.com/validated-changeset/validated-changeset/pull/71%23discussion_r440168238&source=gmail&ust=1592313487179000&usg=AFQjCNFIfSaTYrHv31UtbRfAhf3AhtVCyg
=> Dont unwrap proxy when passing into validator func

src/utils/has-key.ts, test/utils/has-key.test.ts
https://github.com/poteto/ember-changeset/issues/518
=> Fix pathInChanges bug

src/index.ts, test/index.test.ts
ref https://github.com/poteto/ember-changeset/issues/523
=> Improve handling of `changesetKeys` on setProperty

test/index.test.ts
ref https://github.com/poteto/ember-changeset/issues/529
=> Add test for execute with nested object

src/index.ts, src/types/index.ts
=> Throw original error and ensure we dont modify existing

src/index.ts
ref https://github.com/poteto/ember-changeset/issues/543
=> Make isObject overridable

src/index.ts, src/utils/get-deep.ts, src/utils/object-tree-node.ts, test/index.test.ts, test/utils/get-deep.test.ts
ref https://github.com/poteto/ember-changeset/issues/551
```
changeset.get('profile').set('url', value);
```
=> Add chain get/set for ObjectTreeNode

src/index.ts, src/utils/merge-deep.ts, test/index.test.ts
https://github.com/poteto/ember-changeset/issues/552#issuecomment-729711831
=> Protect null case for mergeDeep

test/index.test.ts
ref: https://github.com/poteto/ember-changeset/issues/564
Follow up: https://github.com/validated-changeset/validated-changeset/pull/80
=> Add test for rejected promise

src/utils/flatten-validations.ts, src/utils/handle-multiple-validations.ts, src/utils/validator-lookup.ts, test/index.test.ts
close https://github.com/poteto/ember-changeset/pull/565
=> Bugfix: support multiple validators with classes

src/index.ts, test/index.test.ts
close https://github.com/poteto/ember-changeset/issues/568
=> Handle empty string case

src/index.ts, src/utils/normalize-object.ts, src/utils/object-tree-node.ts, test/utils/object-tree-node.test.ts
plan to handle ember-data objects
ref https://github.com/poteto/ember-changeset/issues/572
=> [Feat]: isObject for unwrap on object tree node

src/utils/normalize-object.ts, test/utils/normalize-object.test.ts
ref https://github.com/poteto/ember-changeset/issues/572
=> [Bug]: prevent cyclical issues with normalizeObject

src/-private/change.ts, src/index.ts, src/types/index.ts, src/utils/get-deep.ts, src/utils/get-key-values.ts, src/utils/has-changes.ts, src/utils/has-key.ts, src/utils/merge-deep.ts, src/utils/normalize-object.ts, src/utils/object-tree-node.ts, src/utils/set-deep.ts, test/index.test.ts, test/utils/get-key-values.test.ts, test/utils/has-key.test.ts, test/utils/object-tree-node.test.ts
=> [Enhancement]: private change detection

src/index.ts, test/index.test.ts
https://github.com/poteto/ember-changeset/pull/580
ref #101
=> Missing isChange detection

src/index.ts, test/index.test.ts
https://github.com/poteto/ember-changeset/pull/579
=> [Enhancement]: initially set PREVIOUS_CONTENT to undefined

src/utils/set-deep.ts
I encountered an issue while trying to execute a changeset whose `data` or `CONTENT` is a proxy, with the typical ember warning 
```log
Error: Assertion Failed: You attempted to access the `shared_schema_template9_9999` property (of <MegamorphicModel:reports:local-156sedjf>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('shared_schema_template9_9999')` in this case.
```
So this PR just uses safeGet for accessing props on the target.
=> use safe-get for accessing target props

src/index.ts, test/index.test.ts
=> [Bug] Same date comparision dirties changeset

src/index.ts, test/index.test.ts
revert - https://github.com/validated-changeset/validated-changeset/pull/123
I was trolled by our external partner tests that were failing.  Trying to unwind.
=> Revert: Rework final phases of get trap

.github/workflows/ci.yml, bin/test-external-changeset.js
I borked #123 :(. I wasn't properly failing the partner test.
=> [CI]: Property fail partner tests

src/utils/key-in-object.ts
ref https://github.com/poteto/ember-changeset/issues/602
Attempting to read and then write will cause issues.
=> Fix Ember tracking issue on set

src/index.ts
https://github.com/poteto/ember-changeset/pull/604/checks?check_run_id=3076413929
=> Bugfix: ensure changesetKeys is passed through in Ember versions > 3.24

package-lock.json, package.json, src/utils/get-key-values.ts, src/utils/merge-nested.ts, src/validated.ts, test/utils/get-key-values.test.ts, test/utils/merge-deep.test.ts, test/utils/normalize-object.test.ts, test/validated.test.ts
fix `execute()`.  New changes format was not compatible.
=> bugfix: execute does not work with new ValidatedChangeset

src/index.ts
Exports array utils functions. It will fix some duplicated code in ember-changeset related to https://github.com/poteto/ember-changeset/issues/657.
=> export array utils functions
